# hash:sha256:d98a5ceefa4a50f8b41b313283aa19e93ce59fb99aabb354ac6ccd92ffbf0c70
FROM registry.codeocean.com/codeocean/miniconda3:4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    beautifulsoup4==4.12.3 \
    google-search-results==2.4.2 \
    huggingface-hub==0.22.2 \
    nltk==3.8.1 \
    numpy==1.26.4 \
    protobuf==5.26.1 \
    python-dateutil==2.9.0.post0 \
    scikit-learn==1.4.2 \
    scipy==1.13.0 \
    sentence-transformers==2.7.0 \
    sentencepiece==0.2.0 \
    sumy==0.11.0 \
    torch==2.3.0
